feminine_coded_words = [
    'feminine', 'beauty', 'floral', 'moisturizers', 'beautiful',
       'trust', 'different', 'match', 'soybean', 'summer', 'incredible',
       'delicate', 'rose', 'soft', 'powder', 'jasmine', 'shaving',
       'conditions', 'magazines', 'needed', 'feels', 'starts',
       'three', 'conditioners', 'favorite', 'moisture', 'additional',
       'discomfort', 'days', 'capsules', 'among', 'controls', 'tested',
       'brand', 'organic', 'soothing', 'fun', 'botanical', 'activity',
       'everyday', 'lady', 'flower', 'unstoppable', 'liquid', 'coverage',
       'create', 'compact', 'toxins', 'type', 'enough',
       'microcrystalline', 'protecting', 'stress', 'smooth', 'shake',
       'gluten', 'anyone', 'little', 'breeze', 'making', 'area',
       'hypoallergenic', 'bring', 'better', 'next', 'pink', 'sold',
       'immediately', 'ricinoleate', 'antioxidant', 'carry', 'heavenly',
       'inviting', 'absorbs', 'light', 'matter', 'extracts',
       'description', 'wide', 'splash', 'cruelty', 'purse', 'essentials',
       'aubrey', 'organics', 'ultra', 'wax', 'gentle', 'suave',
       'certified', 'express', 'calendula', 'soften', 'less', 'tender',
       'intended', 'absorb', 'lavender', 'elegant', 'enjoy', 'products',
       'remove', 'aloe', 'bottle', 'contain', 'lovely', 'gently', 'treat',
       'fda', 'delicately', 'synthetic', 'showering', 'sensitive',
       'designer', 'sensual', 'imposters', 'allowing', 'irritated',
       'benefits', 'infused', 'leaf', 'vera', 'roll', 'mineral',
       'essential', 'inspired', 'tried', 'dermatologically', 'work',
       'causing', 'scented', 'held', 'environmentally', 'breast', 'pg',
       'continuous', 'pineapple', 'ease', 'disclaimer', 'statements',
       'cure', 'purified', 'clinical', 'evaluated', 'diagnose', 'visibly',
       'salts', 'en', 'luxurious', 'deodorizing', 'soothes', 'exotic',
       'chemicals', 'prescription', 'prevent', 'fire', 'shower', 'bright',
       'full', 'friends', 'strong', 'neutralize', 'require', 'gardens',
       'seeking', 'arnica', 'alternative', 'watery', 'breathing', 'areas',
       'research', 'color', 'freshening'
]

f2_words = [u'feminine', u'beauty', u'powder', u'beautiful', u'delicate',
       u'different', u'match', u'soybean', u'incredible', u'rose',
       u'moisture', u'hypoallergenic', u'shaving', u'needed', u'trust',
       u'jasmine', u'soft', u'brand', u'favorite', u'making', u'starts',
       u'salts', u'feels', u'controls', u'suave', u'products',
       u'coverage', u'among', u'tea', u'essential', u'area',
       u'immediately', u'ricinoleate', u'certified', u'p', u'better',
       u'gluten', u'liquid', u'protecting', u'activity', u'elegant',
       u'microcrystalline', u'absorbs', u'days', u'enough', u'type',
       u'botanical', u'calendula', u'leaf', u'compact', u'lady',
       u'tested', u'benefits', u'crystal', u'discomfort', u'smooth',
       u'soothing', u'shake', u'everyday', u'stress', u'conditions',
       u'pink', u'antioxidant', u'anyone', u'splash', u'tried',
       u'capsules', u'mineral', u'light', u'flower', u'remove',
       u'chemicals', u'vera', u'cocoa', u'essentials', u'irritated',
       u'organics', u'en', u'create', u'aubrey', u'bicarbonate',
       u'butter', u'lavender', u'extracts', u'breeze', u'wide',
       u'stopping', u'little', u'laureth', u'luxurious', u'heavenly',
       u'bright', u'contain', u'soften', u'gentle', u'absorb', u'wax',
       u'aloe', u'sensitive', u'baking', u'soda', u'bring', u'less',
       u'roll', u'purse', u'trisolid', u'bed', u'purified',
       u'gently', u'cream', u'inviting', u'clicks', u'neutralize',
       u'cyclomethicone', u'causing', u'enjoy', u'infused',
       u'prescription', u'matter', u'safe', u'selling', u'bottle',
       u'description', u'inhibit', u'healthcare', u'environmentally',
       u'arnica', u'carry', u'ease', u'applying', u'true', u'consult',
       u'three', u'sensual', u'delicately', u'supplements', u'verbena',
       u'properties', u'petrolatum', u'ultra', u'express', u'phthalates',
       u'calming', u'sold', u'cruelty', u'paraben', u'soothes', u'lovely',
       u'alternative', u'following', u'areas', u'wherever', u'cherry',
       u'knowing', u'found', u'pleasant', u'held', u'item', u'entire',
       u'clinical', u'breast', u'color', u'continuous', u'resting',
       u'short', u'work', u'fire', u'scented', u'self',
       u'hints', u'extract', u'shower', u'natural', u'quickly',
       u'moisturizing', u'next', u'unstoppable', u'deodorizing',
       u'tender', u'strong', u'perfect', u'absorbing', u'perfumes',
       u'research', u'parfums', u'winner', u'phenoxyethanol', u'minerals',
       u'coeur', u'barrier', u'dangerous', u'visibly', u'family',
       u'combine', u'toughest', u'exotic', u'recommended', u'alkyl',
       u'form', u'oils', u'love', u'vegetable', u'full', u'crush',
       u'benzoate', u'effectively', u'take', u'acid', u'steareth',
       u'prevent', u'ml', u'glyceryl', u'pineapple', u'plant', u'creamy',
       u'allowing', u'vegan', u'herbal', u'professional', u'touch',
       u'powders', u'odors', u'naturally', u'made', u'citric', u'arms',
       u'oleate', u'addition', u'sweet', u'releasing', u'sunflower',
       u'strength', u'marks', u'stressful', u'schmidt', u'added',
       u'cotton', u'fast', u'bag', u'registered', u'acclimates',
       u'brands', u'school', u'officinalis', u'percent', u'promotes',
       u'watery', u'normal', u'pits', u'bath', u'paraffin', u'award',
       u'wear', u'soja', u'require', u'thats', u'lichen', u'petroleum',
       u'symptoms', u'usually', u'step', u'glycine', u'dietary', u'based',
       u'unpleasant', u'bacteria', u'messy', u'vanilla', u'value',
       u'formulated', u'fragrances', u'last', u'glycerin', u'trace',
       u'clothes', u'dermatologically', u'staining', u'delivers',
       u'drying', u'chemical', u'aroma', u'thin', u'kind', u'away',
       u'may', u'live', u'solids', u'healthy', u'friends', u'handle',
       u'instead', u'pit', u'chlorohydrate', u'crosspolymer', u'expect',
       u'parabens', u'senses', u'count', u'sticky', u'proven',
       u'dimethicone', u'barbadensis', u'friendly', u'means',
       u'hydrolyzed', u'especially', u'arrowroot', u'play', u'times',
       u'developed', u'give', u'glides', u'two', u'white', u'doctor',
       u'expensive', u'given', u'today', u'deterrents', u'holes',
       u'built', u'tripropylene', u'requires', u'point', u'cooling',
       u'eliminating', u'note', u'naturals', u'member', u'freshening',
       u'leading', u'countless', u'look', u'colgate', u'hygiene',
       u'average', u'exciting', u'bikini', u'tube', u'trusted', u'bay',
       u'takes', u'support', u'perfumed', u'alike', u'living',
       u'easily', u'travel', u'normally', u'indications', u'handy',
       u'eliminated', u'convenient', u'even', u'choice', u'applied',
       u'minimize', u'acetate', u'tocopheryl', u'seed', u'helianthus',
       u'vitamin', u'antiperspirants', u'comes', u'feel', u'fits',
       u'promise', u'formulas', u'delightful', u'paradise', u'save',
       u'tropical', u'unisex', u'showering', u'simple', u'whenever',
       u'covering', u'greasy', u'wet', u'without', u'dermatologist',
       u'soothe', u'offers', u'silica', u'grapefruit', u'designer',
       u'sexy', u'offer', u'well', u'years', u'derived', u'annuus',
       u'finish', u'fruity', u'looking', u'zinc', u'control',
       u'specially', u'swallowed', u'vs', u'ask', u'residue',
       u'clinically', u'disease', u'discontinue', u'develops', u'sure',
       u'layer', u'center', u'kidney', u'poison', u'medical', u'ideal',
       u'source', u'refreshed', u'skip', u'fruit', u'apple', u'gel',
       u'cancer', u'reapplication', u'tightly', u'unlike', u'eliminate',
       u'skin', u'seconds', u'forming', u'created', u'imposters',
       u'launched', u'know', u'wetness', u'clothing', u'clean',
       u'including', u'inside', u'jar', u'since', u'captivating',
       u'missing', u'artificial', u'gives', u'mitchum', u'feeling',
       u'aluminum', u'neutralizes', u'helping', u'eliminates', u'formula',
       u'polyethylene', u'irritation', u'morning', u'caused', u'known',
       u'go', u'oil', u'warnings', u'leaving', u'temperature',
       u'protects', u'helps', u'burst', u'trichlorohydrex', u'calcium',
       u'unscented', u'nan', u'worry', u'energy', u'talc',
       u'staying', u'euphorbia', u'momentarily', u'cerifera', u'taken',
       u'intoxicating', u'variety', u'jojoba', u'included',
       u'peony', u'maintain', u'trimmer', u'nucifera', u'coty',
       u'produces', u'ammonium', u'close', u'adds', u'eligible',
       u'jumpstart', u'person', u'read', u'essences', u'chinensis',
       u'coriander', u'lather', u'standards', u'cans']

masculine_coded_words = [
    'spice', 'old', 'guard', 'masculine', 'defense', 'endurance',
       'phoenix', 'axe', 'energized', 'machine', 'climb', 'moisturizer',
       'zone', 'tough', 'put', 'rush', 'freedom', 'apollo', 'sports',
       'armpit', 'answer', 'wash', 'enduring', 'system', 'precision',
       'adventure', 'bodyspray', 'sport', 'magic', 'places', 'energizing',
       'anywhere', 'neck', 'legendary', 'hint', 'wood', 'fiji',
       'irresistible', 'resistant', 'transparent', 'stronger', 'game',
       'got', 'cannot', 'blast', 'high', 'chest', 'cologne', 'seal',
       'lime', 'conditioner', 'fully', 'caught', 'guy', 'freshest',
       'effect', 'transforms', 'song', 'comfort', 'experience', 'arctic',
       'reveal', 'anytime', 'mennen', 'pretty', 'revolutionary', 'whole',
       'taking', 'containing', 'irritant', 'unilever', 'complex', 'chill',
       'spicy', 'rugged', 'come', 'subtle', 'stands', 'seduce', 'warning',
       'dryness', 'blocking', 'focused', 'onto', 'towards', 'brut',
       'together', 'ladies', 'specifically', 'brings', 'sophisticated',
       'anarchy', 'woods', 'slowly', 'sleeves', 'rosemary', 'team',
       'push', 'demands', 'whisper', 'visible', 'excessive', 'bar', 'top',
       'refresh', 'condition', 'tree', 'continue', 'total', 'moments',
       'imagine', 'arm', 'mint', 'open', 'stains', 'ahead', 'bergamot',
       'dark', 'collection', 'base', 'dynamic', 'reborn', 'combusts',
       'refined', 'perspirants', 'enticing', 'herban', 'bird', 'elements',
       'ashes', 'named', 'many', 'promote', 'cowboy', 'definitely',
       'maranta', 'adidas', 'deep', 'expose', 'highest', 'vary',
       'smoking', 'red', 'smell', 'gets', 'line', 'trimax', 'glide',
       'visit', 'shield', 'rich', 'covered', 'range', 'world', 'essence',
       'power', 'fresher', 'information', 'selection', 'mythical',
       'woody', 'casual', 'vetiver', 'woodsy', 'working', 'embrace',
       'toll', 'grow', 'routine', 'centers', 'part', 'oxygen', 'company',
       'practically', 'concern', 'end', 'deliver', 'field', 'soap',
       'situations', 'eco', 'masculinity', 'cedar', 'musky', 'wait',
       'good', 'blue', 'accept', 'ocean', 'applicator', 'realize',
       'includes', 'cool', 'stain', 'turn', 'complete', 'blocks', 'case',
       'ensure', 'powerful', 'performance', 'hot', 'plants',
       'crafted', 'endorsed', 'compromise', 'shine', 'capric', 'simply',
       'style', 'house', 'like', 'musk', 'ever', 'green', 'could',
       'providing', 'stink', 'protective', 'breakthrough', 'geranium',
       'aromas', 'released'
]

m2_words = [u'old', u'spice', u'guard', u'axe', u'defense', u'energized',
       u'machine', u'sports', u'climb', u'zone', u'tough', u'rush',
       u'might', u'bodyspray', u'wood', u'adventure', u'silver', u'sport',
       u'neck', u'energizing', u'transparent', u'enduring', u'high',
       u'places', u'legendary', u'fully', u'complex', u'chest',
       u'anywhere', u'lime', u'stronger', u'experience', u'wash',
       u'system', u'blast', u'resistant', u'wipe', u'irresistible',
       u'got', u'anytime', u'game', u'fiji', u'ladies', u'chill',
       u'answer', u'mint', u'conditioner', u'subtle', u'arctic',
       u'mennen', u'unilever', u'effect', u'cologne', u'specifically',
       u'guy', u'edge', u'large', u'song', u'smoking', u'open', u'reveal',
       u'moments', u'condition', u'blocking', u'irritant', u'put',
       u'comfort', u'focused', u'adidas', u'cedar', u'eco', u'prepare',
       u'team', u'brut', u'whole', u'brings', u'push', u'towards',
       u'revolutionary', u'pretty', u'woody', u'top', u'dark', u'capric',
       u'collection', u'total', u'precision', u'woods', u'irish',
       u'warning', u'containing', u'model', u'taking', u'sage',
       u'continue', u'premium', u'shield', u'expose', u'zesty', u'come',
       u'tree', u'hint', u'red', u'anarchy', u'molecules',
       u'together', u'performance', u'released', u'base', u'promote',
       u'whisper', u'anything', u'situations', u'triclosan',
       u'definitely', u'range', u'ensure', u'six', u'butane', u'bar',
       u'sophisticated', u'oxygen', u'part', u'stains', u'working',
       u'ready', u'caprylic', u'bergamot', u'blue', u'vary', u'hot',
       u'includes', u'fresher', u'smell', u'workout', u'glide',
       u'schedule', u'line', u'grow', u'build', u'place',
       u'freshest', u'powered', u'recycled', u'visible', u'tell',
       u'targets', u'visit', u'impression', u'casual', u'trimax',
       u'demands', u'max', u'cannot', u'tomsofmaine', u'net', u'end',
       u'packs', u'remain', u'microbial', u'strokes', u'good', u'power',
       u'cool', u'ocean', u'world', u'green', u'first', u'soap',
       u'usesreduces', u'ahead', u'seal', u'imagine', u'call', u'blends',
       u'highest', u'deep', u'packaging', u'stain', u'case', u'geranium',
       u'modern', u'refined', u'toll', u'gets', u'sleeves', u'mark',
       u'compromise', u'turn', u'respond', u'ever', u'powerful',
       u'stearate', u'arm', u'conditioning', u'woodsy', u'realize',
       u'essence', u'triple', u'citrus', u'vetiver', u'hydroxide',
       u'pair', u'moment', u'centers', u'perfectly', u'learn',
       u'backpack', u'almost', u'saving', u'field', u'knows', u'shows',
       u'quantity', u'die', u'named', u'spices', u'town', u'fear',
       u'lift', u'believe', u'aromatic', u'stewardship', u'storage',
       u'neat', u'lead', u'embrace', u'distinctive', u'big', u'sharp',
       u'selection', u'button', u'rich', u'like', u'eau', u'plants',
       u'set', u'shine', u'comments', u'musk', u'make', u'www', u'hard',
       u'kissed', u'complete', u'hand', u'could', u'would', u'refresh',
       u'carbonate', u'people', u'style', u'accept', u'yellow', u'new',
       u'quality', u'motion', u'fight', u'let', u'armpits', u'providing',
       u'applicator', u'questions', u'replace', u'information',
       u'deliver', u'gum', u'want', u'lifestyle', u'daily', u'things',
       u'allows', u'says', u'excessive', u'dial', u'raise', u'try',
       u'crisp', u'great', u'entirely', u'enzyme', u'office', u'oriental',
       u'octyldodecanol', u'behind', u'caramel', u'ounces', u'shipping',
       u'meets', u'cut', u'straight', u'hops', u'cuts', u'problem',
       u'kills', u'routine', u'cons', u'sticks', u'simply',
       u'releases', u'guaranteed', u'violet', u'hectorite', u'degree',
       u'extra', u'orange', u'technology', u'possesses', u'peel',
       u'assume', u'sunshine', u'cypress', u'multiple', u'lifetime',
       u'ball', u'flaky', u'currant', u'cocktail', u'impact', u'buy',
       u'bark', u'harmony', u'larger', u'overpowering', u'renowned',
       u'plum', u'lemongrass', u'fig', u'bottles', u'tackle', u'cfcs',
       u'proudly', u'reserved', u'youre', u'cacao', u'rights', u'telling',
       u'razor', u'slow', u'business', u'stickiness', u'eight', u'shave',
       u'date', u'challenge', u'complement', u'tones', u'moss',
       u'bod', u'breaks', u'choose', u'blocks', u'aromas', u'deodorant',
       u'cleaner', u'denat', u'eyes', u'combination', u'stick',
       u'important', u'irritating', u'prevents', u'worn', u'dispenser',
       u'pressure', u'need', u'maine', u'tom', u'benefit', u'market',
       u'breakthrough', u'black', u'store', u'keeps', u'amber',
       u'microcapsules', u'house', u'hair', u'notes', u'maximum',
       u'degrees', u'nature', u'directed', u'classic', u'time', u'stuff',
       u'heart', u'shown', u'mandarin', u'fragranceuses', u'misc',
       u'freshness', u'heading', u'sprays', u'dream', u'addictive',
       u'mean', u'supply', u'stepped', u'blackberry', u'please', u'prod',
       u'many', u'toms', u'items', u'ultraclear', u'protect', u'getting',
       u'covered', u'eucalyptus', u'revlon', u'formulation', u'airy',
       u'corp', u'makes', u'hide', u'combined',
       u'incinerate', u'contents', u'puncture', u'propylene', u'crowd',
       u'avoid', u'back', u'misuse', u'intentional',
       u'concentrating', u'inhaling', u'night', u'deliberately',
       u'parfum', u'instantly', u'combines', u'boost', u'repair', u'head',
       u'one', u'zea', u'mays', u'antibacterial', u'proprietary',
       u'mexico', u'slowly', u'temperatures', u'sense', u'tocopherol',
       u'perspirants', u'sweating', u'hold', u'flame', u'responsive',
       u'protected', u'label', u'sweat', u'easy', u'way', u'shippingpack',
       u'motionsense', u'stink', u'aerosol', u'aqua', u'shirts',
       u'package', u'captures', u'lasts', u'body', u'disteardimonium',
       u'near', u'best', u'secret', u'water',
       u'life', u'dressed', u'smelling', u'lasting', u'fighting', u'care',
       u'amount', u'lemon']

hyphenated_coded_words = [
]

possible_codings = (
    "strongly feminine-coded",
    "feminine-coded",
    "neutral",
    "masculine-coded",
    "strongly masculine-coded"
)

explanations = {
    "feminine-coded": ("This description uses more words that "
                        "are skewed feminine than words that are "
                        "skewed masculine."),
    "masculine-coded": ("This description uses more words that "
                        "skew masculine than words that are "
                        "skew feminine."),
    "strongly feminine-coded": ("This description uses more words that "
                        "are skewed feminine than words that are "
                        "skewed as masculine."),
    "strongly masculine-coded": ("This description uses more words that "
                        "are skewed masculine than words that "
                        "skew feminine."),
    "empty": ("This description doesn't use any words "
              "that are skewed very masculine or feminine."),
    "neutral": ("This description uses approximately equal number "
              "of words that are skewed masculine and feminine.")
}
